server:
  port: 18080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

zuul:
  SendErrorFilter:
    error:
      disable: false
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Allow-Methods
  routes:
    user:
      path: /user/**
    accessory:
      path: /accessory/**
    supplier:
      path: /supplier/**
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

ribbon:
  restclient:
    enable: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

logging:
  level:
    js: debug