server:
  port: 18081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sj?characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      instance:
        prefer-ip-address: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false

logging:
  level:
    sj: debug
